use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug)]
struct TargetDir {
    name: String,
    manifest_path: PathBuf,
    templates: Vec<TemplateFile>,
}

#[derive(Debug)]
struct TemplateFile {
    path: String,
    const_name: String,
    source_path: PathBuf,
}

fn main() {
    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR must be set"));
    let templates_dir = manifest_dir.join("src/templates");
    println!("cargo:rerun-if-changed={}", templates_dir.display());

    let targets = discover_targets(&templates_dir);
    let generated = render_generated_templates_module(&manifest_dir, &targets);
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR must be set"));
    fs::write(out_dir.join("templates_generated.rs"), generated)
        .expect("write generated codegen template registry");
}

fn discover_targets(templates_dir: &Path) -> Vec<TargetDir> {
    let mut targets = fs::read_dir(templates_dir)
        .expect("read codegen templates directory")
        .filter_map(Result::ok)
        .filter(|entry| !entry.path().join(".disabled").is_file())
        .map(|entry| entry.path())
        .filter(|path| path.is_dir() && path.join("target.toml").is_file())
        .map(|dir| discover_target_dir(&dir))
        .collect::<Vec<_>>();
    targets.sort_by(|lhs, rhs| lhs.name.cmp(&rhs.name));
    targets
}

fn discover_target_dir(dir: &Path) -> TargetDir {
    let name = dir
        .file_name()
        .and_then(|name| name.to_str())
        .expect("target directory must have UTF-8 name")
        .to_string();
    let manifest_path = dir.join("target.toml");
    let mut templates = fs::read_dir(dir)
        .expect("read target template directory")
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| path.extension().and_then(|ext| ext.to_str()) == Some("jinja"))
        .map(|source_path| {
            let path = source_path
                .file_name()
                .and_then(|name| name.to_str())
                .expect("template file must have UTF-8 name")
                .to_string();
            TemplateFile {
                const_name: generated_template_const_name(&name, &path),
                path,
                source_path,
            }
        })
        .collect::<Vec<_>>();
    templates.sort_by(|lhs, rhs| lhs.path.cmp(&rhs.path));
    validate_manifest_templates(&manifest_path, &templates);
    TargetDir {
        name,
        manifest_path,
        templates,
    }
}

fn validate_manifest_templates(manifest_path: &Path, templates: &[TemplateFile]) {
    let manifest = fs::read_to_string(manifest_path).expect("read target manifest");
    for referenced in manifest_template_references(&manifest) {
        if !templates.iter().any(|template| template.path == referenced) {
            eprintln!(
                "{} references missing template {}",
                manifest_path.display(),
                referenced
            );
            std::process::exit(1);
        }
    }
}

fn manifest_template_references(manifest: &str) -> Vec<String> {
    manifest
        .lines()
        .filter_map(|line| {
            let trimmed = line.trim();
            let value = trimmed.strip_prefix("template")?.trim();
            let value = value.strip_prefix('=')?.trim();
            let value = value.strip_prefix('"')?;
            let end = value.find('"')?;
            Some(value[..end].to_string())
        })
        .collect()
}

fn render_generated_templates_module(manifest_dir: &Path, targets: &[TargetDir]) -> String {
    let mut out = String::from("// @generated by build.rs; do not edit by hand.\n\n");
    for target in targets {
        render_target_constants(&mut out, manifest_dir, target);
    }
    for target in targets {
        render_target_template_array(&mut out, target);
    }
    render_builtin_targets(&mut out, targets);
    out
}

fn render_target_constants(out: &mut String, manifest_dir: &Path, target: &TargetDir) {
    let manifest_const = generated_manifest_const_name(&target.name);
    let manifest_path = include_path(manifest_dir, &target.manifest_path);
    out.push_str(&format!(
        "const {manifest_const}: &str = include_str!(\"{manifest_path}\");\n"
    ));
    for template in &target.templates {
        let include_path = include_path(manifest_dir, &template.source_path);
        out.push_str(&format!(
            "const {}: &str = include_str!(\"{}\");\n",
            template.const_name, include_path
        ));
    }
    out.push('\n');
}

fn render_target_template_array(out: &mut String, target: &TargetDir) {
    let array_const = generated_target_templates_const_name(&target.name);
    out.push_str(&format!(
        "const {array_const}: &[BuiltinTargetTemplate] = &[\n"
    ));
    for template in &target.templates {
        out.push_str(&format!(
            "    BuiltinTargetTemplate {{ path: \"{}\", source: {} }},\n",
            template.path, template.const_name
        ));
    }
    out.push_str("];\n\n");
}

fn render_builtin_targets(out: &mut String, targets: &[TargetDir]) {
    out.push_str("pub const BUILTIN_TARGETS: &[BuiltinTarget] = &[\n");
    for target in targets {
        out.push_str(&format!(
            "    BuiltinTarget {{ name: \"{}\", manifest: {}, templates: {} }},\n",
            target.name,
            generated_manifest_const_name(&target.name),
            generated_target_templates_const_name(&target.name)
        ));
    }
    out.push_str("];\n");
}

fn include_path(manifest_dir: &Path, path: &Path) -> String {
    let _ = manifest_dir;
    path.to_string_lossy().replace('\\', "/")
}

fn generated_manifest_const_name(target: &str) -> String {
    format!("{}_TARGET_MANIFEST", screaming_identifier(target))
}

fn generated_target_templates_const_name(target: &str) -> String {
    format!("{}_TARGET_TEMPLATES", screaming_identifier(target))
}

fn generated_template_const_name(target: &str, template: &str) -> String {
    format!(
        "{}_{}",
        screaming_identifier(target),
        screaming_identifier(template)
    )
}

fn screaming_identifier(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    let mut last_was_separator = true;
    for ch in input.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_uppercase());
            last_was_separator = false;
        } else if !last_was_separator {
            out.push('_');
            last_was_separator = true;
        }
    }
    while out.ends_with('_') {
        out.pop();
    }
    out
}
